export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_DETAIL_REQUEST = 'PRODUCT_DETAIL_REQUEST';
export const PRODUCT_DETAIL_SUCCESS = 'PRODUCT_DETAIL_SUCCESS';
export const PRODUCT_DETAIL_FAIL = 'PRODUCT_DETAIL_FAIL';

export const PRODUCT_LIST_PAGINATE_REQUEST = 'PRODUCT_LIST_PAGINATE_REQUEST';
export const PRODUCT_LIST_PAGINATE_SUCCESS = 'PRODUCT_LIST_PAGINATE_SUCCESS';
export const PRODUCT_LIST_PAGINATE_FAIL = 'PRODUCT_LIST_PAGINATE_FAIL';

export const REVIEW_LIST_REQUEST = 'REVIEW_LIST_REQUEST';
export const REVIEW_LIST_SUCCESS = 'REVIEW_LIST_SUCCESS';
export const REVIEW_LIST_FAIL = 'REVIEW_LIST_FAIL';

export const REVIEW_ADD_REQUEST = 'REVIEW_ADD_REQUEST';
export const REVIEW_ADD_SUCCESS = 'REVIEW_ADD_SUCCESS';
export const REVIEW_ADD_FAIL = 'REVIEW_ADD_FAIL';
export const REVIEW_ADD_RESET = 'REVIEW_ADD_RESET';

export const REVIEW_DEL_REQUEST = 'REVIEW_DEL_REQUEST';
export const REVIEW_DEL_SUCCESS = 'REVIEW_DEL_SUCCESS';
export const REVIEW_DEL_FAIL = 'REVIEW_DEL_FAIL';

export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL';

export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const USER_SIGNOUT_REQUEST = 'USER_SIGNOUT_REQUEST';
export const USER_SIGNOUT_SUCCESS = 'USER_SIGNOUT_SUCCESS';
